//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmlakOtomasyonManisa
{
    using System;
    using System.Collections.Generic;
    
    public partial class evler
    {
        public int id { get; set; }
        public string emlakTipi { get; set; }
        public Nullable<int> alan { get; set; }
        public string odaSayisi { get; set; }
        public Nullable<int> binaYasi { get; set; }
        public Nullable<int> binaKatSayisi { get; set; }
        public Nullable<int> bulunduguKat { get; set; }
        public Nullable<int> daireKacKatli { get; set; }
        public string isitma { get; set; }
        public Nullable<int> banyoSayisi { get; set; }
        public string esyalı { get; set; }
        public string siteIcerisinde { get; set; }
        public Nullable<int> aidat { get; set; }
        public Nullable<int> fiyat { get; set; }
        public string ilanLinki { get; set; }
        public string adres { get; set; }
        public string daireNotu { get; set; }
        public Nullable<int> evSahibiCariID { get; set; }
        public Nullable<int> eviKiralayanCariID { get; set; }
    
        public virtual cariler cariler { get; set; }
        public virtual cariler cariler1 { get; set; }
    }
}
